### ISSUE TITLE
Missing Linux binary for 0.0.2

### ISSUE THREAD

**Issue by dmarcoux** [aviaviavi/confetti#5]
The title says it all.

Nice update by the way 👍

**Comment by aviaviavi** [comment]
Thanks for pointing this out, and glad you think so! I had a little technical difficulties with my linux vm this morning which prevented me from getting a build out. I'll get that sorted out shortly and get that uploaded 😄

**Comment by dmarcoux** [comment]
I'm quite a newbie with Haskell and I'm wondering something. How are you creating your binaries?

You might be already using it, but [haskell-builder](https://github.com/dkubb/haskell-builder) seems great.

**Comment by aviaviavi** [comment]
Oooh I've actually never seen this before, pretty cool! I'll give this a spin when I have a chance. Thanks for the suggestion.

I currently just build the binaries manually with `stack` on my mac and linux machines separately, and upload them. Since there has been so few releases I haven't spent too much time trying to optimize/automate that process. But I definitely have been curious about the Right™ way to do that too. This seems like a great way to get the linux binary built on my mac, and then it could all be scripted nicely.

**Comment by aviaviavi** [comment]
Linux binary is uploaded!
